/*
    To test in httpyac w/ vscodium...
    open the command pallette (C-S-p)
    first run `> Test: Clear All Results`
    then run `> Test: Run All Tests`

    For a more granular approach...
    Hover each item individually and do C-M-r
*/

@assetsDir=./

###
# @name json_session
POST http://{{BASE_URL}}/api/v1/session

?? status == 201

###
# @ref json_session
GET http://{{BASE_URL}}/api/v1/session/{{json_session.rpghp_session_id}}

?? status == 200

###
# @ref json_session
POST http://{{BASE_URL}}/api/v1/session/{{json_session.rpghp_session_id}}/creature
Authorization: Bearer {{json_session.secret}}
Content-Type: application/json
< {{assetsDir}}jon_visible.json

?? status == 201

###
# @ref json_session
POST http://{{BASE_URL}}/api/v1/session/{{json_session.rpghp_session_id}}/creature
Authorization: Bearer {{json_session.secret}}
Content-Type: application/json
< {{assetsDir}}jon_hidden.json

?? status == 201

###
# @ref json_session
GET http://{{BASE_URL}}/api/v1/session/{{json_session.rpghp_session_id}}/creature

?? status == 200
?? body contains "jon visible"
?? body contains "jon hidden"

###
# @ref json_session
GET http://{{BASE_URL}}/api/v1/session/{{json_session.rpghp_session_id}}/creature
Authorization: Bearer {{json_session.secret}}

?? status == 200

###
# @ref json_session
DELETE http://{{BASE_URL}}/api/v1/session/{{json_session.rpghp_session_id}}
Authorization: Bearer {{json_session.secret}}

?? status == 200
